### PR TITLE
League stats

### PR DESCRIPTION
**Pull request by CrowRising**
oooo weeeeeee burning that pre midnight oil
let's def get a second and third set of eyes on this to make sure my late night construction will hold.

You know I messed it up again and tried to bypass our main branch xoxoxo forgive me

### CODE REVIEW

**Review by thawley2 — COMMENTED** [review]
I think we should wait to merge this to main until the branch you created is completed with the methods for the tests written.

**Review by andrew-bingham1 — COMMENTED** [review]
Agree with Thomas per our group discussion, lets do this as a branch of a branch thing for practice

**Comment by CrowRising** [comment]
YES I get why we shouldn't merge this yet. Makes total sense. Once we get methods written and merged to this branch THEN I will make a new pull request

**Comment by andrew-bingham1** [comment]
Okay per comments above we will close this until league is complete

**Pull request closed without merging**
