### PR TITLE
Refactor: create a module for the league_stat class helper methods

### PR DESCRIPTION
**Pull request by angelbyun**
Created a module to hold all of the helper methods for the league_stats class

### CODE REVIEW

**Review by CrowRising — APPROVED** [review]
Hooray!!!!!

**Review by thawley2 — APPROVED** [review]
Nice job with the module!

**Review by andrew-bingham1 — APPROVED** [review]
Looks very clean with the helper methods in a module! Nice work!

**Comment by CrowRising** [comment]
It was great that we all got experience in creating a module

**Pull request merged**
