### PR TITLE
Refactor game stats

### PR DESCRIPTION
**Pull request by thawley2**
Refactored game_stats class with helper methods.  Added helper method tests to keep our %100 coverage.

### CODE REVIEW

**Review by CrowRising — APPROVED** [review]
These look great Thomas! I also enjoyed being able to talk with you last night while you were working on these and get to see a little of your process. I definitely think this would be a great opportunity to use a module as well.

**Review by angelbyun — APPROVED** [review]
The refactoring looks great!!! Great job on refactoring the average_goals_by_season method!!!!

**Review by andrew-bingham1 — CHANGES_REQUESTED** [review]
Per our call lets see if we can use modules here for practice

**Review by CrowRising — APPROVED** [review]
The module was success! Good work team

**Review by andrew-bingham1 — APPROVED** [review]
Nice job Andrew, really knocking it out of the park

**Pull request merged**
